### ISSUE TITLE
item.type as a <li> class name

### ISSUE THREAD

**Issue by entinio** [TinyWisp/twtree#14]
Any chance to add the type (`item.type`) to the `<li>` class ?

```
:class="{
              'twtree-node':                true, 
              'twtree-node-selected':       item.selected,
```
(...)
```
              'twtree-node-drag-over-self': item.__.dragOverArea === 'self' && item.__.isDroppable,
              item.type
            }"
```

This way we could easily change the style of a specific type element (like the font color, which isn't part of the style properties)

**Comment by TinyWisp** [comment]
As of twtree 3.7.0, I added the fnCustomClasses property.
see https://tinywisp.github.io/twtree/#/en/example/custom-appearance/custom-classes for more information.

**Comment by entinio** [comment]
That's perfect ! Thanx
