### ISSUE TITLE
fnCustomClasses() and create()

### ISSUE THREAD

**Issue by entinio** [TinyWisp/twtree#17]
When using the `create()` method, the new node doesn't seem to cycle through the `fnCustomClasses()` property function to apply any custom style depending on the new node values.

Might be interesting to add a `refreshCustomClasses()` method to call right after creating a new node, method that could be used to update any change around the displayed values?

**Comment by TinyWisp** [comment]
https://codepen.io/tinywisp/pen/XWgZdPR
In this example, the fnCustomClasses works well on the new created nodes. 

I don't think the refreshCustomClasses() method is necessary. may be the refresh() method is what you want.

there was a bug, which would lead to some outdated properties of the node passed to fnCustomClasses, and I fixed it in twtree 3.8.0.
try twtree 3.8.0. if it doesn't work, maybe you can call the refresh() method manually.

**Comment by TinyWisp** [comment]
https://codepen.io/tinywisp/pen/XWgZdPR
In this example, the fnCustomClasses works well on the new created nodes.

I don't think the refreshCustomClasses() method is necessary. may be the refresh() method is what you want.

there was a bug, which would lead to some outdated properties of the node passed to fnCustomClasses, and I fixed it in twtree 3.8.1.
try twtree 3.8.1. if it doesn't work, maybe you can call the refresh() method manually.

**Comment by entinio** [comment]
Thank you for your great answer as always. It needed that update that I missed.
