### ISSUE TITLE
Start as minimized

### ISSUE THREAD

**Issue by bajki** [TinyWisp/twtree#18]
How to setup not expand all categories on start.

If i have large dataset i don't want to show everything only on click.

**Comment by TinyWisp** [comment]
try this

``
:defaultAttrs="{directoryState: 'expanded'}"
``

see these links for more information:
https://tinywisp.github.io/twtree/#/en/example/getting-started/set-props
https://github.com/TinyWisp/twtree/wiki/Document#how-to-set-properties-for-all-the-nodes
https://github.com/TinyWisp/twtree/wiki/Document#twtree-node-properties
