### ISSUE TITLE
Css UI defect when using RTL

### ISSUE THREAD

**Issue by darkman97i** [TinyWisp/twtree#24]
Hi,
I'm using bootstrap and bootstrap rtl in my application. I share some screenshots for better understanding of the behaviour when I change to RTL.

Standard view:
![Selección_035](https://user-images.githubusercontent.com/958703/163552578-3241398f-9322-447f-9ca7-57ada08d51a5.png)

is this the only css you are using in the application?
https://github.com/TinyWisp/twtree/blob/master/docs/css/app.be5292d3.css

![Selección_036](https://user-images.githubusercontent.com/958703/163553186-766a40d9-9db9-4077-92ee-626e52d2fdaa.png)

looking in the code seems you are using the styles like the next to set left space for each node in the tree.
* "--fullIndent:calc(30px);"
* "--fullIndent:calc(30px + 30px);"
* "--fullIndent:calc(30px + 30px + 30px);"

Meanwhile I'm trying to look for a fix from my side to do not apply RTL in the tree, any help is welcome.

Thanks for your time.

**Comment by TinyWisp** [comment]
https://codepen.io/tinywisp/pen/MWrzJEy
is this what you need?

> is this the only css you are using in the application?
> https://github.com/TinyWisp/twtree/blob/master/docs/css/app.be5292d3.css
the /docs folder is where I put the static files for [demos](https://tinywisp.github.io/twtree/#/en/) site.
besides the component's styles, the /docs/css/app.be5292d3.css includes the styles used in these demos.
