### ISSUE TITLE
复选框checkboxLinkage的配置可否增加更细粒度的控制

### ISSUE THREAD

**Issue by anrananran** [TinyWisp/twtree#29]
比如选择节点或取消选择节点时，可以单独配置是否影响父级，是否影响子级，或都影响？

**Comment by TinyWisp** [comment]
最近没太上github，没看到你提的问题，不好意思。

能否详细说明一下，你需要什么样的细粒度控制？

**Comment by anrananran** [comment]
Y 属性定义 checkbox 被勾选后的情况；
N 属性定义 checkbox 取消勾选后的情况；
"p" 表示操作会影响父级节点；
"s" 表示操作会影响子级节点。
举个例子： 
`<twtree :checkbox-linkage="{ Y: 'ps', N: 's' }"  />` 
表示勾选节点时同时影响父级节点和子级节点，取消勾选时只影响子级节点

`<twtree :checkbox-linkage="{ Y: '', N: 'p' }"  />` 
表示勾选节点时既不影响父级节点、也不影响子级节点，取消勾选时只影响父级节点

`<twtree :checkbox-linkage="{ Y: 's', N: '' }"  />` 
表示勾选节点时只影响子级节点，取消勾选时既不影响父级节点、也不影响子级节点

`<twtree :checkbox-linkage="{ Y: '', N: '' }"  />` 等价于 `<twtree :checkbox-linkage="false"  />`
表示无论勾选还是取消勾选节点都不影响父级也不影响子级

**Comment by TinyWisp** [comment]
你所描述的功能可能不太通用，因此没有在组上按你所说的更改。

我写了一个示例，是用现有的功能，去实现“只影响子级结点”“只影响父级结点”“既不影响父级结点，也不影响子级结点”等功能
https://codepen.io/tinywisp/pen/eYMQyvB

**Comment by anrananran** [comment]
好的，这个功能确实不太常用，如果有类似需求我直接用示例中的方式来做，感谢回复！
