### ISSUE TITLE
Whether to support mobile touch screen dragging

### ISSUE THREAD

**Issue by lilanping** [TinyWisp/twtree#33]
Whether to support mobile touch screen dragging

**Comment by TinyWisp** [comment]
I'm sick and weak now. I'll think about it several days later.

**Comment by TinyWisp** [comment]
according to your github id, I think that you are chinese, and speaking chinese is much better for our communication.
根据你的github id， 我猜你是中国人，由于我的英文也不是很好，我们说中文的话会更加有利于沟通。

从4.2.0版本起，已经支持触屏。

这儿有几个触屏示例的链接：
https://tinywisp.github.io/twtree/#/zh/example/drag-and-drop-with-touch-support/basic
https://tinywisp.github.io/twtree/#/zh/example/drag-and-drop-with-touch-support/advanced
https://tinywisp.github.io/twtree/#/zh/example/drag-and-drop-with-touch-support/drag-a-node-out
https://tinywisp.github.io/twtree/#/zh/example/drag-and-drop-with-touch-support/drop-an-external-element
https://tinywisp.github.io/twtree/#/zh/example/drag-and-drop-with-touch-support/multiple-trees

如果用手机查看上述示例，用手指点击屏幕空白处，会展开或隐藏左侧菜单。

主要是要加上属性`:enableTouchSupport="true"`
如果不涉及将外部元素拖动到树中，或将树中结点拖动到树的外部，用法和鼠标拖拽操作基本一致。
