### ISSUE TITLE
自定义自定义外观的几处问题

### ISSUE THREAD

**Issue by ying911008** [TinyWisp/twtree#4]
你好，使用过程发现几处问题：
一：自定义外观的例子中：有些没申明v-slot:；
二：v-slot:title 设置最长宽度超过即用省略号表示：无法达到超过左侧剩余宽度就用省略号的效果
三：v-slot:extra 这个是不是可以考虑增加一个选项，一直显示，而不是鼠标滑过

**Comment by TinyWisp** [comment]
你好，谢谢你的反馈！

第1点没太明白，是说在自定义外观的页面里，有些slot没有示例吗？

第2点:  增加了属性node.stytle.titleMaxWidth, node.style.titleOverflow属性，并在自定义外观中添加了相应示例，文档中也添加了这两个属性的说明。
第3点:  增加了属性node.style.extraAlwaysVisible属性，并在自定义外观中添加了相应示例，文档中也添加了这个属性的说明。

**Comment by ying911008** [comment]
> 你好，谢谢你的反馈！
> 
> 第1点没太明白，是说在自定义外观的页面里，有些slot没有示例吗？
> 
> 第2点: 增加了属性node.stytle.titleMaxWidth, node.style.titleOverflow，并在自定义外观中添加了相应示例，文档中也添加了这两个属性的说明。
> 第3点: 增加了属性node.style.extraAlwaysVisible，并在自定义外观中添加了相应示例，文档中也添加了这个属性的说明。

你好：
1.<div class="title">drag and drop</div>这个示例，是不是有写法错误，没有对title添加上slot，修改不起作用
2.node.stytle.titleMaxWidth这个我试了下，好像不起作用，另外关于这个属性，是否可以不统一固定长度，而是有个百分比，例如title长度为满铺到最右侧，超过twtree最大宽度就用省略号，而且是否需要再加个titleMinWidth属性

**Comment by TinyWisp** [comment]
用户在拖动一个结点时，鼠标旁边会显示一个图像，自定义外观中的drag and drop这个示例是用来自定义这个图像的，所以用的slot是drag-image。

titleMaxWidth属性，这个实际上是设置了max-width这个css属性，所以理论上是可以用百分比的，但我还没实际测试过，不好妄言，因为实际情况中百分比是受父容器影响。

当前在自定义外观示例中，最后一个例子使用了titleMaxWidth，现在twtree的版本号已经升到了1.3.0，你看下是不是版本问题。

title长度满铺到最右端，超过则显示省略号，当前还没有这个功能，晚上我下班后看看。

**Comment by ying911008** [comment]
> 用户在拖动一个结点时，鼠标旁边会显示一个图像，自定义外观中的drag and drop这个示例是用来自定义这个图像的，所以用的slot是drag-image。
> 
> titleMaxWidth属性，这个实际上是设置了max-width这个css属性，所以理论上是可以用百分比的，但我还没实际测试过，不好妄言，因为实际情况中百分比是受父容器影响。
> 
> 当前在自定义外观示例中，最后一个例子使用了titleMaxWidth，现在twtree的版本号已经升到了1.3.0，你看下是不是版本问题。
> 
> title长度满铺到最右端，超过则显示省略号，当前还没有这个功能，晚上我下班后看看。
titleMaxWidth用百分比这个我本来想直接修改你的源码，用flex布局来做，貌似现在的结构不好实现，版本我是升级到1.3.0的，因为3这个功能已经可以实现了

**Comment by TinyWisp** [comment]
版本升到1.3.1，titleMaxWidth可以使用百分比了，之前使用百分比的时候显示效果不太正确。

**Comment by ying911008** [comment]
> 版本升到1.3.1，titleMaxWidth可以使用百分比了，之前使用百分比的时候显示效果不太正确。

你好，
我升级了下1.3.1，出问题了，自定义的图标都出现了问题，百分比好像也没起作用，tree的外框也被固定了，之前没有限制tree的宽度他会随着内容变大，感觉还是之前的效果能满足好，我退回1.3.0了
链接:https://pan.baidu.com/s/1XtJlMJjzFZCzcz_CsPAqiA  提取码: q483

**Comment by ying911008** [comment]
退不回去了，求作者大大解决下，有点害怕

**Comment by TinyWisp** [comment]
谢谢反馈！
我这边用chrome, firefox, edge都试了下，难以复现问题。
你先用1.3.0吧。

**Comment by TinyWisp** [comment]
版本1.4.0，treeMaxWidth可以设置为一个负值，表示距右边缘的距离。
“自定义外观”中已增加相应示例。
文档也已经更新。

**Comment by TinyWisp** [comment]
近期发现拖放功能存在一个问题，在2.2.0中修复。
如果你在生产环境中用到了拖放功能，请注意升级。
