### ISSUE TITLE
如何在选中节点下添加新节点呢？

### ISSUE THREAD

**Issue by wonderfulo** [TinyWisp/twtree#5]

**Comment by TinyWisp** [comment]
这儿有个示例：https://tinywisp.github.io/twtree/#/example/basic
源码：https://github.com/TinyWisp/twtree/blob/master/src/views/BasicExample.vue

这个示例的源码中有个方法create，代码如下：
```javascript
    create() {
      this.counter += 1
      let tree = this.$refs.tree
      let node = tree.getSelectedOne()
      let child = {
        id:  this.counter,
        title: 'hello, world!' + this.counter,
        hasChild: false
      }
      tree.create(child, node)
    },
```
let node = tree.getSelectedOne()是获取选中的结点
tree.create(child, node)是添加结点

添加结点时，结点的id属性如果不提供，则会自动生成一个id

**Comment by wonderfulo** [comment]
谢谢 作者 (*￣︶￣)
