### ISSUE TITLE
does it work with vue3?

### ISSUE THREAD

**Issue by ishaqj** [TinyWisp/twtree#8]
Hi, im wondering if twtree works with Vue 3?

**Comment by TinyWisp** [comment]
it doesn't work with vue 3 currently!  the next version that works with vue3 is about to come in a few weeks.

**Comment by TinyWisp** [comment]
tree component for vue 3
https://github.com/TinyWisp/vue-tree

**Comment by TinyWisp** [comment]
tree component for vue 3
https://github.com/TinyWisp/vue-tree
